name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - sympy
  - pandas
  - bokeh
  - ipyvolume
  - IPython
  - ipywidgets
  - jupyter_contrib_nbextensions
  - ipympl
  - nodejs

